# Generated by Django 5.0.1 on 2024-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=122)),
                ('RN', models.CharField(max_length=122)),
                ('DOB', models.DateField()),
                ('Email', models.CharField(max_length=122)),
                ('MN', models.IntegerField()),
                ('Gen', models.CharField(max_length=122)),
                ('Caddr', models.CharField(max_length=122)),
                ('Paddr', models.CharField(max_length=122)),
                ('Ftname', models.CharField(max_length=122)),
                ('Email1', models.CharField(max_length=122)),
                ('MN1', models.IntegerField()),
                ('Mtname', models.CharField(max_length=122)),
                ('Email2', models.CharField(max_length=122)),
                ('MN2', models.IntegerField()),
                ('Stdmentor', models.CharField(max_length=122)),
                ('EmailM', models.CharField(max_length=122)),
                ('MNstdm', models.IntegerField()),
                ('Factmentor', models.CharField(max_length=122)),
                ('EmailF', models.CharField(max_length=122)),
                ('MNfactm', models.IntegerField()),
                ('dep', models.CharField(max_length=122)),
            ],
        ),
    ]
