# Generated by Django 5.0.1 on 2024-01-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='MN',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pd',
            name='MN1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pd',
            name='MN2',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pd',
            name='MNfactm',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pd',
            name='MNstdm',
            field=models.CharField(max_length=12),
        ),
    ]
