# Generated by Django 5.0.1 on 2024-01-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_pd_mn_alter_pd_mn1_alter_pd_mn2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pd',
            new_name='pdM',
        ),
    ]
