# Generated by Django 5.0.1 on 2024-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_pd_pdm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdm',
            name='MN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pdm',
            name='MN1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pdm',
            name='MN2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pdm',
            name='MNfactm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pdm',
            name='MNstdm',
            field=models.IntegerField(null=True),
        ),
    ]
