# Generated by Django 5.0.1 on 2024-02-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attm',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.pdm'),
        ),
    ]
