# Generated by Django 5.0.1 on 2024-02-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_attm_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attm',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pdm'),
        ),
    ]
