# Generated by Django 5.0.1 on 2024-02-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_attm_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='adM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adSem', models.CharField(max_length=122)),
                ('at1', models.IntegerField(null=True)),
                ('at2', models.IntegerField(null=True)),
                ('ia1', models.IntegerField(null=True)),
                ('ia2', models.IntegerField(null=True)),
                ('prelim', models.IntegerField(null=True)),
                ('endsem', models.IntegerField(null=True)),
                ('perf', models.CharField(max_length=122)),
            ],
        ),
    ]
