# Generated by Django 5.0.1 on 2024-02-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_adm_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm',
            name='adSem',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
