# Generated by Django 5.0.1 on 2024-02-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_adm_adsem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm',
            name='adSem',
            field=models.CharField(max_length=50),
        ),
    ]
