# Generated by Django 5.0.1 on 2024-02-25 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_adm_adsem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adm',
            unique_together={('adSem', 'user')},
        ),
    ]
