# Generated by Django 5.0.1 on 2024-02-25 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_cocurricular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoCurricular',
            new_name='cocuM',
        ),
    ]
