# Generated by Django 5.0.1 on 2024-02-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_cocurricular_cocum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cocum',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cocum',
            name='sem',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='cocum',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.pdm'),
        ),
        migrations.RemoveField(
            model_name='cocum',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='cocum',
            name='user',
        ),
    ]
