# Generated by Django 5.0.1 on 2024-02-25 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_cocum_unique_together_cocum_sem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocum',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pdm'),
        ),
        migrations.CreateModel(
            name='excoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(default=1, max_length=20)),
                ('sports', models.TextField()),
                ('nss', models.TextField()),
                ('price', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pdm')),
            ],
        ),
    ]
