# Generated by Django 5.0.1 on 2024-02-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_cocum_user_profile_excom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excom',
            old_name='sem',
            new_name='exsem',
        ),
    ]
