# Generated by Django 5.0.1 on 2024-02-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_excom_exsem'),
    ]

    operations = [
        migrations.CreateModel(
            name='plcM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(max_length=122)),
                ('package', models.CharField(max_length=122)),
                ('semester', models.CharField(max_length=122)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pdm')),
            ],
        ),
    ]
