# Generated by Django 5.0.1 on 2024-02-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_plcm_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plcm',
            old_name='user',
            new_name='user_profile',
        ),
    ]
