# Generated by Django 5.0.1 on 2024-02-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_user_plcm_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plcm',
            old_name='user_profile',
            new_name='user',
        ),
    ]
