# Generated by Django 5.0.1 on 2024-03-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
