# Generated by Django 5.0.1 on 2024-03-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plcm',
            name='user',
        ),
    ]
