# Generated by Django 5.0.1 on 2024-03-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_plcm_user_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdmM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FnameM', models.CharField(max_length=122)),
                ('IDM', models.CharField(max_length=122)),
                ('DOBM', models.DateField()),
                ('EmailM', models.CharField(max_length=122)),
                ('MNM', models.CharField(max_length=122)),
                ('GenM', models.CharField(max_length=122)),
                ('depM', models.CharField(max_length=122)),
            ],
        ),
    ]
