# Generated by Django 5.0.1 on 2024-04-26 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gre', models.CharField(max_length=122)),
                ('tofel', models.CharField(max_length=122)),
                ('cat', models.CharField(max_length=122)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='higher_std', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
