# Generated by Django 5.0.1 on 2024-04-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_hsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsm',
            name='others',
            field=models.CharField(default=1, max_length=122),
        ),
    ]
